apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sherlock.fullname" . }}
  labels:
    {{- include "sherlock.labels" . | nindent 4 }}
data:
{{- with .Values.config }}
  config.yaml: | {{ tpl (toYaml .) $ | nindent 4 }}
{{- end }}
