apiVersion: v2
type: application
name: cloud
version: v0.0.1
appVersion: v0.0.1
description: Agent Helm chart for datasherlocks cloud
keywords:
  - datasherlocks
home: https://datasherlocks.io
sources:
  - https://github.com/datasherlocks/datasherlocks
maintainers:
  - name: datasherlocks
    url: https://datasherlocks.io
kubeVersion: ">=1.16.0-0"
